version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: resume_match_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {YOUR PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  resume-backend:
    build: .
    container_name: resume_match_backend
    environment:
      PORT: 3000
      DB_HOST: ls-8788ed0f1d26274e6ca65981fab3dc40b86aad05.cu54g4ogoqcd.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: {YOUR PASSWORD}

      # Embedding provider
      EMBEDDING_PROVIDER: bedrock

      # AWS Bedrock credentials
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BEDROCK_MODEL: ${AWS_BEDROCK_MODEL}

      # Cognito
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}

    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: npm start

volumes:
  postgres_data:
